# Base runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

# Build and publish stage
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore student-management-dotnet.sln
RUN dotnet publish student-management-dotnet.csproj -c Release -o /app/publish

# Final image
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .  # đúng path sau khi publish
ENTRYPOINT ["dotnet", "student-management-dotnet.dll"]
